# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://7colou.red
gitlocation: https://github.com/cannorin/cannorin.github.io.git
gitbranch: main
title: SevenColoured
subtitle: 
description: 
source: src/
blog: src/blog/
blogIndex: src/blog/index.cshtml
layouts: layouts
content: content
template: tools/empty-template.html
output: output/
deploy: deploy
themes: themes
